server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://192.168.12.85:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: IamWild!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file: /logs/stock_service.log
  level:
    org.springfromework.web: info
    org.hibernate: error
